# Hel Chart.yaml -> the Chart.yaml file is required for a chart (chart.yson)
apiVersion: v2
name: backend
version: 1.0.0 # Chart Version
description:  This is backend deployment
appVersion: 1.0.0 #backendd app version
